[tools]
bun = "latest"
chezmoi = "latest"
codex = "latest"
deno = "latest"
gh = "latest"
go = "latest"
java = "temurin-25"
node = "26.7.0"
"npm:@angular/cli" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@nestjs/cli" = "latest"
"npm:neovim" = "latest"
opencode = "latest"
pnpm = "latest"
python = "latest"
rust = "stable"
