# ==============================================================================
# Hyprland Main Configuration (CachyOS / Arch Linux)
# ==============================================================================

# Si existen las fuentes base empaquetadas por CachyOS (cachyos-hyprland-settings), cargarlas:
source = ~/.config/hypr/config/environment.conf
source = ~/.config/hypr/config/variables.conf
source = ~/.config/hypr/config/animations.conf
source = ~/.config/hypr/config/decorations.conf
source = ~/.config/hypr/config/input.conf
source = ~/.config/hypr/config/monitor.conf
source = ~/.config/hypr/config/keybinds.conf
source = ~/.config/hypr/config/windowrules.conf
source = ~/.config/hypr/config/autostart.conf

# Personalizaciones de usuario gestionadas con Chezmoi:
source = ~/.config/hypr/user-config.conf
